# Bugfix: Sweep
# ------------------
# We noticed that the 'sweep' function was not behaving as expected under certain conditions.
# Specifically, the bug was located in the 'file.py' module, where the sweep function was not
# handling a specific edge case properly.
#
# This bugfix introduces a conditional statement to handle the missing edge case, ensuring
# that the sweep function behaves as expected in all scenarios.
#
# Labels: sweep
